plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'ezra4ka'
version = '0.1'

base {
    archivesName = 'SVFurniture-api'
}

repositories {
    mavenCentral()
    maven {
        name = 'papermc-repo'
        url = uri('https://repo.papermc.io/repository/maven-public/')
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
    withJavadocJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(21)
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
}